### ISSUE TITLE
[FUZZ] SyntaxError in lodestar_enr

### ISSUE THREAD

**Issue by Daft-Wullie** [sigp/beacon-fuzz#41]
I've identified a fuzzer crash and am contributing to the security of Ethereum 2!

## I've done and provided the following:
- [x] Checked to see if any other `[FUZZ]` issue already refers to that crasher
- [x] Attached the crashing input (either attached to the issue as a .zip or .gz, or as a link to a file sharing service)
- [x] Noted the `beacon-fuzz` version or commit used.
- [x] Provided crash output
- [x] Noted the command or fuzzer used to generate the crash
- [x] Name of the original crash file
- [ ] (Optional but optimal) Checked if the crash can be consistently replicated by re-running the input. 

## Info to Reproduce
* Command run: `make fuzz-all`
* Crasher file name: crash-72910cbc72ffcfe532837c1e78a40ce5bf2be7d724cccefc3e34557a17de7353
[crash-72910cbc72ffcfe532837c1e78a40ce5bf2be7d724cccefc3e34557a17de7353-lodestar_enr.zip](https://github.com/sigp/beacon-fuzz/files/4922858/crash-72910cbc72ffcfe532837c1e78a40ce5bf2be7d724cccefc3e34557a17de7353-lodestar_enr.zip)
* Client exercised: Lodestar
* Fuzzing engine used (if applicable): jsfuzz

## Crash output and stacktrace

```#5308 PULSE     cov: 6733 corp: 3147 exec/s: 189 rss: 300.96 MB
#5374 NEW     cov: 6736 corp: 3148 exec/s: 179 rss: 300.96 MB
=================================================================
SyntaxError: Cannot convert 0x",\,X,
,M��h@�B�N���,?�� to a BigInt
    at BigInt (<anonymous>)
    at Object.toBigIntBE (/eth2fuzz/node_modules/bigint-buffer/dist/node.js:1:5633)
    at Function.decodeFromValues (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26148)
    at Function.decode (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26556)
    at Function.decodeTxt (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26863)
    at Object.fuzz_lodestar_enr (/eth2fuzz/workspace/targets/js/lib.js:1:9181)
    at Worker.fuzz [as fn] (/eth2fuzz/workspace/jsfuzz/lodestar_enr.js:1:1039)
    at process.<anonymous> (/usr/lib/node_modules/jsfuzz/build/src/worker.js:63:30)
    at process.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
crash was written to crash-72910cbc72ffcfe532837c1e78a40ce5bf2be7d724cccefc3e34557a17de7353
Worker exited
```

## Your Environment
* Fuzzer ran: eth2fuzzer
* Version/Commit used: e55cdfe
* Operating System and version: Ubuntu 20.04

**Comment by pventuzelo** [comment]
Congratz, look valid to me. 
Reported here: https://github.com/ChainSafe/discv5/issues/71

**Comment by MysticRyuujin** [comment]
Here's another:
```
=================================================================
SyntaxError: Cannot convert 0x
,0, to a BigInt
    at BigInt (<anonymous>)
    at Object.toBigIntBE (/eth2fuzz/node_modules/bigint-buffer/dist/node.js:1:5633)
    at Function.decodeFromValues (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26148)
    at Function.decode (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26556)
    at Function.decodeTxt (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26863)
    at Object.fuzz_lodestar_enr (/eth2fuzz/workspace/targets/js/lib.js:1:9181)
    at Worker.fuzz [as fn] (/eth2fuzz/workspace/jsfuzz/lodestar_enr.js:1:1039)
    at process.<anonymous> (/usr/lib/node_modules/jsfuzz/build/src/worker.js:63:30)
    at process.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
crash was written to crash-3bea1e427c001cc6085396e697a3f89e0b0f33c9d20c2ff3dd5f6279069c9257
crash(hex)=656e723a3f000000364444444444444444444444444444444444444444444444
Worker exited
```

**Comment by pventuzelo** [comment]
@MysticRyuujin I confirm it is the same bug ;)
