### ISSUE TITLE
[FUZZ] lodestar - Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/beacon-fuzz#48]
I've identified a fuzzer crash and am contributing to the security of Ethereum 2!

## I've done and provided the following:
- [x] Checked to see if any other `[FUZZ]` issue already refers to that crasher
- [x] Attached the crashing input (either attached to the issue as a .zip or .gz, or as a link to a file sharing service)
- [x] Noted the `beacon-fuzz` version or commit used.
- [x] Provided crash output
- [x] Noted the command or fuzzer used to generate the crash
- [x] Name of the original crash file
- [ ] (Optional but optimal) Checked if the crash can be consistently replicated by re-running the input. 

## Info to Reproduce
* Command run: e.g. `eth2fuzz_lodestar continuously --infinite --filter lodestar`
* Crasher file name: `crash-d89e24778114bb05e5541d096cd86dba4ab6ce3f5ca71394fa757868c07ede7b`
* Client exercised: `lodestart`
* Fuzzing engine used (if applicable):

## Crash output and stacktrace
[d89e24778114bb05e5541d096cd86dba4ab6ce3f5ca71394fa757868c07ede7b.zip](https://github.com/sigp/beacon-fuzz/files/4933898/d89e24778114bb05e5541d096cd86dba4ab6ce3f5ca71394fa757868c07ede7b.zip)

```console
enr:,0Q
```

```console
=================================================================
TypeError: Cannot read property 'toString' of undefined
    at Object.toBigIntBE (/eth2fuzz/node_modules/bigint-buffer/dist/node.js:1:5452)
    at Function.decodeFromValues (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26148)
    at Function.decode (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26556)
    at Function.decodeTxt (/eth2fuzz/node_modules/@chainsafe/discv5/lib/enr/enr.js:1:26863)
    at Object.fuzz_lodestar_enr (/eth2fuzz/workspace/targets/js/lib.js:1:8102)
    at Worker.fuzz [as fn] (/eth2fuzz/workspace/jsfuzz/lodestar_enr.js:1:1039)
    at process.<anonymous> (/usr/lib/node_modules/jsfuzz/build/src/worker.js:63:30)
    at process.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
crash was written to crash-d89e24778114bb05e5541d096cd86dba4ab6ce3f5ca71394fa757868c07ede7b
crash(hex)=656e723a2c3051
Worker exited
```

## Your Environment

* Fuzzer ran: `eth2fuzz_lodestar continuously --infinite --filter lodestar`
* Version/Commit used: `f4e4baebb6be13350e4dacce096c16bd7b50635f`
* Operating System and version: Running in docker on Windows Subsystem for Linux 2 / Ubuntu 20.04 LTS

**Comment by zedt3ster** [comment]
Thanks @MysticRyuujin and congratulations on spotting a valid bug on Lodestar! This has been raised with the Lodestar development team in [this issue](https://github.com/ChainSafe/discv5/issues/71). Closing this issue at it is a duplicate of #52.
