### ISSUE TITLE
[FUZZ] Crash encountered in prysm_attestation

### ISSUE THREAD

**Issue by Daft-Wullie** [sigp/beacon-fuzz#54]
I've identified a fuzzer crash and am contributing to the security of Ethereum 2!

## I've done and provided the following:
- [x] Checked to see if any other `[FUZZ]` issue already refers to that crasher
- [x] Attached the crashing input (either attached to the issue as a .zip or .gz, or as a link to a file sharing service)
- [x] Noted the `beacon-fuzz` version or commit used.
- [x] Provided crash output
- [x] Noted the command or fuzzer used to generate the crash
- [x] Name of the original crash file
- [ ] (Optional but optimal) Checked if the crash can be consistently replicated by re-running the input. 

## Info to Reproduce
* Command run: `make fuzz-all`
* Crasher file name: crash-0068a4be4ec62bb9feed5e1dbb57945ed8d9898d
[crash-0068a4be4ec62bb9feed5e1dbb57945ed8d9898d.zip](https://github.com/sigp/beacon-fuzz/files/4981621/crash-0068a4be4ec62bb9feed5e1dbb57945ed8d9898d.zip)

* Client exercised: Prysm
* Fuzzing engine used (if applicable): gofuzz

## Crash output and stacktrace

```#3892791        REDUCE ft: 714 corp: 37/20Kb exec/s: 7647 rss: 67Mb L: 187/4096 MS: 5 ChangeBit-InsertRepeatedBytes-EraseBytes-InsertByte-EraseBytes-
#3957209        REDUCE ft: 714 corp: 37/20Kb exec/s: 7639 rss: 67Mb L: 239/4096 MS: 3 ShuffleBytes-InsertByte-EraseBytes-
#4194304        pulse  ft: 714 corp: 37/20Kb exec/s: 7653 rss: 67Mb
#4485120        NEW    ft: 715 corp: 38/20Kb exec/s: 7640 rss: 67Mb L: 229/4096 MS: 1 ChangeBit-
runtime: unexpected return pc for runtime.gcBgMarkWorker called from 0x0
stack: frame={sp:0xc000448f60, fp:0xc000448fd8} stack=[0xc000448000,0xc000449000)
000000c000448e60:  000000c000449aa8  00000000004c80c4 <runtime.memclrNoHeapPointers+308>
000000c000448e70:  0000000000000202  002b000000000033
000000c000448e80:  0000000000000000  0000000000000000
000000c000448e90:  0000000000000000  0000000000000000
000000c000448ea0:  000000c000448f80  0000000003aec301
000000c000448eb0:  000000c0009c1912  0000000000000004
000000c000448ec0:  0000000000000000  0000000000003200
000000c000448ed0:  00000000000000c8  000000c0009c8060
000000c000448ee0:  0000000003aec340  0000000000000000
000000c000448ef0:  0000000003aec340  000000c000448f50
000000c000448f00:  000000000047e5dc <runtime.gcMarkDone+652>  0000000003ae50f4
000000c000448f10:  3ff07e7be5e23b00  0000000000000000
000000c000448f20:  00040d6248a80252  000000c000082480
000000c000448f30:  000000c000448f50  0000000000499a56 <runtime.gopark+230>
000000c000448f40:  0000000001700270  000000c000448f37
000000c000448f50:  000000c000448fc8  000000000047f335 <runtime.gcBgMarkWorker+261>
000000c000448f60: <0000000001700100  000000c0004e4000
000000c000448f70:  0000000000001418  0000000000000000
000000c000448f80:  000000000000037f  00007f0896b5eedb
000000c000448f90:  0000000000000000  0000ffff00001fa0
000000c000448fa0:  0000000000000000  0000000000000000
000000c000448fb0:  0000000000000000  0000000000000000
000000c000448fc0:  0000000000000000  0000000000000000
000000c000448fd0: !0000000000000000 >0000000000000000
000000c000448fe0:  0000000000000000  0000000000000000
000000c000448ff0:  8800000000000000  0000000000004003
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x11afb22, 0x11)
        runtime/panic.go:1116 +0x74
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc0004e2000, 0x0, 0x0, 0x7fffffff, 0x7f084b7fdb58, 0x0, 0x0, ...)
        runtime/traceback.go:273 +0x19ff
runtime.scanstack(0xc0004e2000, 0xc00003f698)
        runtime/mgcmark.go:739 +0x162
runtime.markroot.func1()
        runtime/mgcmark.go:226 +0xc3
runtime.markroot(0xc00003f698, 0x14)
        runtime/mgcmark.go:199 +0x2f5
runtime.gcDrain(0xc00003f698, 0x3)
        runtime/mgcmark.go:999 +0x10b
runtime.gcBgMarkWorker.func2()
        runtime/mgc.go:1940 +0x82
runtime.systemstack(0x0)
        runtime/asm_amd64.s:370 +0x63
runtime.mstart()
        runtime/proc.go:1041

goroutine 12 [GC worker (idle)]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:330 fp=0xc000049760 sp=0xc000049758 pc=0x4c4ea0
runtime.gcBgMarkWorker(0xc00003e000)
        runtime/mgc.go:1927 +0x1c6 fp=0xc0000497d8 sp=0xc000049760 pc=0x47f3f6
runtime.goexit()
        runtime/asm_amd64.s:1373 +0x1 fp=0xc0000497e0 sp=0xc0000497d8 pc=0x4c6fe1
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1821 +0x79

goroutine 17 [runnable, locked to thread]:
runtime.goexit()
        runtime/asm_amd64.s:1373 +0x1

goroutine 6 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00026c240)
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0xe1
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x13a

goroutine 7 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0000354a0)
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0x248
created by github.com/dgraph-io/ristretto.NewCache
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x2da

goroutine 8 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00024a360)
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0xe1
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x13a

goroutine 9 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000035620)
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0x248
created by github.com/dgraph-io/ristretto.NewCache
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x2da

goroutine 10 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000384480)
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0xe1
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x13a

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0000357a0)
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0x248
created by github.com/dgraph-io/ristretto.NewCache
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x2da

goroutine 50 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0000a2030)
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0xe1
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x13a

goroutine 51 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00008e420)
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0x248
created by github.com/dgraph-io/ristretto.NewCache
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x2da

goroutine 52 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3ae48e0)
        k8s.io/klog@v1.0.0/klog.go:1010 +0xab
created by k8s.io/klog.init.0
        k8s.io/klog@v1.0.0/klog.go:411 +0xf6

goroutine 53 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3ae49c0)
        k8s.io/klog/v2@v2.0.0/klog.go:1107 +0xab
created by k8s.io/klog/v2.init.0
        k8s.io/klog/v2@v2.0.0/klog.go:416 +0xf6

goroutine 68 [select, 3 minutes]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc0004f6830, 0xc000718680)
        github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x113
created by github.com/patrickmn/go-cache.runJanitor
        github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xba

goroutine 69 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001a1110)
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0xe1
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x13a

goroutine 70 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0004e0ea0)
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0x248
created by github.com/dgraph-io/ristretto.NewCache
        github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x2da

goroutine 65 [select, 10 minutes]:
github.com/prysmaticlabs/prysm/shared/runutil.RunEvery.func1(0xc000101810, 0x1dc3878, 0x44, 0x16fe618, 0x172e180, 0xc00003a028)
        github.com/prysmaticlabs/prysm/shared/runutil/every.go:20 +0x1c5
created by github.com/prysmaticlabs/prysm/shared/runutil.RunEvery
        github.com/prysmaticlabs/prysm/shared/runutil/every.go:18 +0x166
==3051== ERROR: libFuzzer: deadly signal
    #0 0x462633  (/eth2fuzz/workspace/gofuzz/prysm_attestation.libfuzzer+0x462633)
    #1 0x4194d6  (/eth2fuzz/workspace/gofuzz/prysm_attestation.libfuzzer+0x4194d6)
    #2 0x41952f  (/eth2fuzz/workspace/gofuzz/prysm_attestation.libfuzzer+0x41952f)
    #3 0x7f089689689f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1289f)
    #4 0x4c8c20  (/eth2fuzz/workspace/gofuzz/prysm_attestation.libfuzzer+0x4c8c20)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 3 ChangeByte-ChangeASCIIInt-InsertByte-; base unit: 6b7a17a04f61755db97a4294c7fc94611b05ce58
0xe4,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x97,0x0,0x0,0x0,0x76,0xc6,0x7f,0x60,0x73,0xa4,0x9e,0xa1,0x64,0xc4,0xfd,0x2c,0xdd,0x7c,0xf8,0x78,0xe2,0x98,0xe1,0x14,0x7a,0xdc,0x0,0x78,0xec,0x1c,0x36,0x74,0x30,0x76,0x55,0x77,0x92,0x67,0xd4,0x70,0xda,0xdf,0xed,0x16,0xa9,0x93,0x1e,0x22,0xe2,0x98,0xe1,0x14,0x7a,0xdc,0x0,0x78,0xec,0x1c,0x33,0x3a,0x30,0x76,0x55,0x77,0xac,0x5a,0x5b,0xa9,0xc4,0x69,0xd0,0xd4,0xf1,0x32,0x91,0x3f,0xb,0x63,0xec,0xb0,0x45,0x75,0xe2,0x2,0x89,0x79,0xcf,0x24,0x4d,0x69,0xeb,0x22,0x79,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xb8,0x7c,0x28,0xfb,0x53,0x13,0xd5,0x45,0x29,0x11,0x87,0x2d,0x24,0xef,0xe6,0x70,0xc4,0xc0,0x92,0x49,0xe8,0x4f,0xdc,0xe7,0x96,0xa8,0x77,0x88,0xa5,0xd9,0xb7,0xff,0x8,0x1,
\xe4\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x97\x00\x00\x00v\xc6\x7f`s\xa4\x9e\xa1d\xc4\xfd,\xdd|\xf8x\xe2\x98\xe1\x14z\xdc\x00x\xec\x1c6t0vUw\x92g\xd4p\xda\xdf\xed\x16\xa9\x93\x1e\"\xe2\x98\xe1\x14z\xdc\x00x\xec\x1c3:0vUw\xacZ[\xa9\xc4i\xd0\xd4\xf12\x91?\x0bc\xec\xb0Eu\xe2\x02\x89y\xcf$Mi\xeb\"y\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb8|(\xfbS\x13\xd5E)\x11\x87-$\xef\xe6p\xc4\xc0\x92I\xe8O\xdc\xe7\x96\xa8w\x88\xa5\xd9\xb7\xff\x08\x01
artifact_prefix='./'; Test unit written to ./crash-0068a4be4ec62bb9feed5e1dbb57945ed8d9898d
Base64: 5AAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlwAAAHbGf2BzpJ6hZMT9LN18+HjimOEUetwAeOwcNnQwdlV3kmfUcNrf7Rapkx4i4pjhFHrcAHjsHDM6MHZVd6xaW6nEadDU8TKRPwtj7LBFdeICiXnPJE1p6yJ5AAAAAAAAAAAAAAAAAAAAALh8KPtTE9VFKRGHLSTv5nDEwJJJ6E/c55aod4il2bf/CAE=
Fuzzer failed so we'll continue with the next one
```

## Your Environment
* Fuzzer ran: eth2fuzz
* Version/Commit used: latest
* Operating System and version: Ubuntu 20.04

**Comment by pventuzelo** [comment]
Thanks for the report. Sadly, I'm not able to reproduce :s

Maybe an error inside the fuzzer or inside golang runtime...
