### ISSUE TITLE
[FUZZ] Beaconfuzz_v2 crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087 in struct_voluntary_exit

### ISSUE THREAD

**Issue by Daft-Wullie** [sigp/beacon-fuzz#73]
I've identified a fuzzer crash and am contributing to the security of Ethereum 2!

## I've done and provided the following:
- [x] Checked to see if any other `[FUZZ]` issue already refers to that crasher
- [x] Attached the crashing input (either attached to the issue as a .zip or .gz, or as a link to a file sharing service)
- [x] Noted the `beacon-fuzz` version or commit used.
- [x] Provided crash output
- [x] Noted the command or fuzzer used to generate the crash
- [x] Name of the original crash file
- [x] (Optional but optimal) Checked if the crash can be consistently replicated by re-running the input.

## Info to Reproduce
* Command run: e.g. `make fuzz_voluntary_exit-struct`
* Crasher file name: crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087
[5d768f7e8462aa1cbeb699c81d5b92b0bdbad087.zip](https://github.com/sigp/beacon-fuzz/files/5182661/5d768f7e8462aa1cbeb699c81d5b92b0bdbad087.zip)

* Client exercised: prysm(?)
* Fuzzing engine used : libfuzzer

## Crash output and stacktrace

```#256    pulse  cov: 1215 ft: 1292 corp: 14/287b lim: 49 exec/s: 12 rss: 365Mb
thread '<unnamed>' panicked at '[PRYSM] Mismatch post', /root/beacon-fuzz/beaconfuzz_v2/libs/prysm/src/voluntary_exit.rs:58:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last, using override)
/root/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(614) signalHandler
SIGABRT: Abnormal termination.
==172729== ERROR: libFuzzer: fuzz target exited
    #0 0x5596293a6901  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xb7f901)
    #1 0x55962b635f20  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e0ef20)
    #2 0x55962b640d6b  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e19d6b)
    #3 0x7fa3cfd97a26  (/lib/x86_64-linux-gnu/libc.so.6+0x49a26)
    #4 0x7fa3cfd97bdf  (/lib/x86_64-linux-gnu/libc.so.6+0x49bdf)
    #5 0x55962961e4b7  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xdf74b7)
    #6 0x7fa3cfd9420f  (/lib/x86_64-linux-gnu/libc.so.6+0x4620f)
    #7 0x7fa3cfd9418a  (/lib/x86_64-linux-gnu/libc.so.6+0x4618a)
    #8 0x7fa3cfd73858  (/lib/x86_64-linux-gnu/libc.so.6+0x25858)
    #9 0x55962b6e6976  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2ebf976)
    #10 0x55962b6cfa05  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2ea8a05)
    #11 0x55962b6051c6  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2dde1c6)
    #12 0x55962b6d6d17  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2eafd17)
    #13 0x5596296d96e4  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xeb26e4)
    #14 0x5596296d9289  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xeb2289)
    #15 0x5596296d9584  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xeb2584)
    #16 0x5596296e2b3c  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xebbb3c)
    #17 0x5596296e337c  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xebc37c)
    #18 0x55962950929d  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xce229d)
    #19 0x55962944aa36  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xc23a36)
    #20 0x55962b6051f0  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2dde1f0)
    #21 0x55962b604e4f  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2ddde4f)
    #22 0x55962b6411cc  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e1a1cc)
    #23 0x55962b6491b0  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e221b0)
    #24 0x55962b649b6c  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e22b6c)
    #25 0x55962b64bf6f  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e24f6f)
    #26 0x55962b613249  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2dec249)
    #27 0x5596293234b6  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xafc4b6)
    #28 0x7fa3cfd750b2  (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #29 0x55962932365d  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xafc65d)

SUMMARY: libFuzzer: fuzz target exited
MS: 3 InsertRepeatedBytes-CrossOver-InsertRepeatedBytes-; base unit: 65248fb8df71097b719f6cc5e600e78a4c795b0a
0x8a,0x8a,0x8a,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8a,0xff,0xff,0xff,0x62,0xff,0xff,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xff,0xff,0xff,0x7f,0xff,0xff,0xff,0x0,0xff,
\x8a\x8a\x8a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8a\xff\xff\xffb\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\x7f\xff\xff\xff\x00\xff
artifact_prefix='/root/beacon-fuzz/beaconfuzz_v2/fuzz/artifacts/struct_voluntary_exit/'; Test unit written to /root/beacon-fuzz/beaconfuzz_v2/fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087
Base64: ioqKAAAAAAAAAAAAAAAAAIr///9i//8AAAAAAAAAAAAAAAD///9/////AP8=

────────────────────────────────────────────────────────────────────────────────

Failing input:

        fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087

Output of `std::fmt::Debug`:

        SignedVoluntaryExit {
            message: VoluntaryExit {
                epoch: Epoch(9079434),
                validator_index: 0,
            },
            signature: 0x8affffff62ffff000000000000000000000000ffffff7fffffff00ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
        }

Reproduce with:

        cargo fuzz run struct_voluntary_exit fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087

Minimize test case with:

        cargo fuzz tmin struct_voluntary_exit fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087


────────────────────────────────────────────────────────────────────────────────

```
output of  ``` ETH2FUZZ_BEACONSTATE=../eth2fuzz/workspace/corpora/beaconstate cargo +nightly fuzz run struct_voluntary_exit fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087 ```

```
    Finished release [optimized] target(s) in 0.16s
     Running `fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit -artifact_prefix=/root/beacon-fuzz/beaconfuzz_v2/fuzz/artifacts/struct_voluntary_exit/ fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087`
INFO: Seed: 626043332
INFO: Loaded 1 modules   (201074 inline 8-bit counters): 201074 [0x55f8b4d3b9a1, 0x55f8b4d6cb13),
INFO: Loaded 1 PC tables (201074 PCs): 201074 [0x55f8b4d6cb18,0x55f8b507e238),
fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit: Running 1 inputs 1 time(s) each.
Running: fuzz/artifacts/struct_voluntary_exit/crash-5d768f7e8462aa1cbeb699c81d5b92b0bdbad087
ERRO[0018] Could not get rough time result: no reply     prefix=roughtime
ERRO[0018] Could not get rough time result: no reply     prefix=roughtime
ERRO[0018] Could not get rough time result: no reply     prefix=roughtime
ERRO[0018] Could not get rough time result: no reply     prefix=roughtime
ERRO[0018] Could not get rough time result: no reply     prefix=roughtime
ERRO[0018] Could not get rough time result: no reply     prefix=roughtime
ERRO[0018] Failed to calculate roughtime offset          error="no valid responses" prefix=roughtime
INFO[0018] New calculated roughtime offset is 0 ns       prefix=roughtime
thread '<unnamed>' panicked at '[PRYSM] Mismatch post', /root/beacon-fuzz/beaconfuzz_v2/libs/prysm/src/voluntary_exit.rs:58:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last, using override)
/root/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(614) signalHandler
SIGABRT: Abnormal termination.
==173964== ERROR: libFuzzer: fuzz target exited
    #0 0x55f8b19a3901  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xb7f901)
    #1 0x55f8b3c32f20  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e0ef20)
    #2 0x55f8b3c3dd6b  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e19d6b)
    #3 0x7f95bd02ea26  (/lib/x86_64-linux-gnu/libc.so.6+0x49a26)
    #4 0x7f95bd02ebdf  (/lib/x86_64-linux-gnu/libc.so.6+0x49bdf)
    #5 0x55f8b1c1b4b7  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xdf74b7)
    #6 0x7f95bd02b20f  (/lib/x86_64-linux-gnu/libc.so.6+0x4620f)
    #7 0x7f95bd02b18a  (/lib/x86_64-linux-gnu/libc.so.6+0x4618a)
    #8 0x7f95bd00a858  (/lib/x86_64-linux-gnu/libc.so.6+0x25858)
    #9 0x55f8b3ce3976  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2ebf976)
    #10 0x55f8b3ccca05  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2ea8a05)
    #11 0x55f8b3c021c6  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2dde1c6)
    #12 0x55f8b3cd3d17  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2eafd17)
    #13 0x55f8b1cd66e4  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xeb26e4)
    #14 0x55f8b1cd6289  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xeb2289)
    #15 0x55f8b1cd6584  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xeb2584)
    #16 0x55f8b1cdfb3c  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xebbb3c)
    #17 0x55f8b1ce037c  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xebc37c)
    #18 0x55f8b1b0629d  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xce229d)
    #19 0x55f8b1a47a36  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xc23a36)
    #20 0x55f8b3c021f0  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2dde1f0)
    #21 0x55f8b3c01e4f  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2ddde4f)
    #22 0x55f8b3c3e1cc  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2e1a1cc)
    #23 0x55f8b3c04e09  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2de0e09)
    #24 0x55f8b3c0ec02  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0x2deac02)
    #25 0x55f8b19204b6  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xafc4b6)
    #26 0x7f95bd00c0b2  (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #27 0x55f8b192065d  (/root/beacon-fuzz/beaconfuzz_v2/fuzz/target/x86_64-unknown-linux-gnu/release/struct_voluntary_exit+0xafc65d)

SUMMARY: libFuzzer: fuzz target exited
────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit code: 77

```
## Your Environment
* Fuzzer ran: beaconfuzz_v2 libfuzzer
* Version/Commit used: b29a20a
* Operating System and version: Ubuntu 20.04

**Comment by Daft-Wullie** [comment]
invalid crash report due to misconfigured user env, closing.
